### ISSUE TITLE
Default cache directory

### ISSUE THREAD

**Issue by sigo** [tschaub/grunt-gh-pages#39]
What about set `clone: 'node_modules/grunt-gh-pages/.cache/<branch>/'` by default? Many grunt packages use `node_modules` directory to keep cache etc.

Advantage of this is that users doesn't need additional line in `.gitignore` file. Just `node_modules/`.

Btw. maybe name of this variable should be `cache` instead of `clone`? It maybe confusing.

**Comment by sigo** [comment]
Does anyone already read this issue?

**Comment by tschaub** [comment]
@sigo using `.grunt` was based on [advice from the Grunt folks](http://gruntjs.com/creating-plugins#storing-task-files).  I agree it is inconvenient, and that the installation directory itself is a nicer place.  I'd gladly accept a pull request that renamed `clone` to `cache` and changed the default location.
