### ISSUE TITLE
Support for grunt v1.0.1

### ISSUE THREAD

**Issue by niemyjski** [tschaub/grunt-gh-pages#60]
Everything seems to work but I get the warning message: 
`npm WARN grunt-gh-pages@1.0.0 requires a peer of grunt@~0.4.1 but none was installed.`

**Comment by tschaub** [comment]
This was addressed with #57.  I just published 1.1.0 with this change.  So if you install the latest, the warning should go away.  Please reopen if not.

**Comment by niemyjski** [comment]
Thanks!
