### ISSUE TITLE
Update graceful-fs version

### ISSUE THREAD

**Issue by FezVrasta** [tschaub/grunt-gh-pages#65]
> (node:49378) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

May you be so kind to update graceful-fs to the latest version please?

**Comment by tschaub** [comment]
Update published with `grunt-gh-pages@1.2`.

**Comment by FezVrasta** [comment]
Thanks for the quick response, just updated the dep and the warning gone, great :)

**Comment by tschaub** [comment]
If you're using Node 4+, you should also be able to upgrade to `grunt-gh-pages@2` to get rid of the deprecation warning about `wrench`.  Things should still work on older Node, but tests are no longer run below Node 4 in the 2.x release.

**Comment by FezVrasta** [comment]
Ah great thanks!
